[package]
name = "capture-card-screenshot"
version = "0.1.0"
edition = "2024"

[dependencies]
msgbox = "0.7.0"
regex = "1.11.1"
thiserror = "2.0.12"
clipboard-rs = "0.3.0"

[dependencies.nokhwa]
git = "https://github.com/l1npengtul/nokhwa"
branch = "0.10"
features = ["input-native"]
